### ISSUE TITLE
NE POZABI!

### ISSUE THREAD

**Issue by MatijaDolzan** [MatijaDolzan/Praktikum7#6]
Blockchain
FB prijava
Alternativna prijava
Docker

**Comment by BrodMatic** [comment]
Blockchain - BigchainDB verjetno najboljša izbira
FB prijava - zanemarimo - ni ravno najboljša platforma za naš tip aplikacije
Google prijava - nadomesti FB prijavo
Alternativna prijava - dokončana.
Docker - NE POZABITI
